<a href="https://colab.research.google.com/github/SilvestreFer/numpy-workbook/blob/main/random_slopes_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Practice Notebook (Exercises)**
---
This file contains practice exercises covering the following topics:
- Creating arrays
- Using arange()
- Vectorized operations
- Computing slopes/intercepts
- Norms and distances
- Random number generation

Each section contains small challenges solved.

In [65]:
import numpy as np
import time

EXERCISE 1 — Creating Arrays

1. Create a NumPy array with the years from 2000 to 2050.
2. Create an array containing the multiples of 4 between 1980 and 2100.
3. Create an array with 50 values equally spaced between 0 and 1.

In [66]:
#1
years_array = np.arange(2000, 2051)
print('Array containing the years from 2000 to 2050.')
print(years_array)
time.sleep(1)

#2
multiples_array = np.arange(1980, 2101, 4)
print('Array containing the multiples of 4 between 1980 and 2100.')
print(multiples_array)
time.sleep(1)

#3
lin_array = np.linspace(0, 1, 50)
print('Array with 50 values equally spaced between 0 and 1.')
print(lin_array)

Array containing the years from 2000 to 2050.
[2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013
 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027
 2028 2029 2030 2031 2032 2033 2034 2035 2036 2037 2038 2039 2040 2041
 2042 2043 2044 2045 2046 2047 2048 2049 2050]
Array containing the multiples of 4 between 1980 and 2100.
[1980 1984 1988 1992 1996 2000 2004 2008 2012 2016 2020 2024 2028 2032
 2036 2040 2044 2048 2052 2056 2060 2064 2068 2072 2076 2080 2084 2088
 2092 2096 2100]
Array with 50 values equally spaced between 0 and 1.
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204

EXERCISE 2 — Vectorized Operations

Given the list:
values = [2, 4, 6, 8, 10]


1. Convert it to a NumPy array.
2. Compute the square of each element.
3. Compute the square root of each element.
4. Add 5 to all elements.

In [67]:
#1
list_values = [2, 4, 6, 8, 10]
array_values = np.array(list_values)
print('Array from list:')
print(array_values)
time.sleep(1)

#2
squares = np.square(array_values)
print('Array of squares:')
print(squares)
time.sleep(1)

#3
roots = np.sqrt(array_values)
print('Array of square roots:')
print(roots)
time.sleep(1)

#4
array_plus_5 = array_values + 5
print('Array with 5 added to all elements:')
print(array_plus_5)

Array from list:
[ 2  4  6  8 10]
Array of squares:
[  4  16  36  64 100]
Array of square roots:
[1.41421356 2.         2.44948974 2.82842712 3.16227766]
Array with 5 added to all elements:
[ 7  9 11 13 15]


EXERCISE 3 — List vs NumPy Timing

1. Create a list with 1,000,000 numbers.
2. Convert it to a NumPy array.
3. Time the operation of cubing each number in the list vs in NumPy.
4. Print both times.

In [68]:
#1
one_million_list = list(range(1000000))

#2
one_million_array = np.array(one_million_list)

#3
# Time the operation of cubing each number in the list
list_start_time = time.time()
list_cubed = [i**3 for i in one_million_list]
list_time = time.time() - list_start_time

# Time the operation of cubing each number in the NumPy array
array_start_time = time.time()
array_cubed = one_million_array**3
array_time = time.time() - array_start_time

#4
print("Time for the list operation: ", list_time)
print("Time for the array operation: ", array_time)

Time for the list operation:  0.1472463607788086
Time for the array operation:  0.00436711311340332


EXERCISE 4 — Computing a Linear Regression Manually

Given:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 4, 5, 4, 5])


1. Compute the slope 'a'.
2. Compute the intercept 'b'.
3. Compute predicted values Y_pred.
4. Compute the error norm: ||Y - Y_pred||.

In [69]:
# Data
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 4, 5, 4, 5])
n = np.size(Y)

#1
a = (n*np.sum(X*Y)-np.sum(X)*np.sum(Y))/(n*np.sum(X**2)-(np.sum(X))**2)
print('Slope "a":', a)

#2
b = np.mean(Y) - a*np.mean(X)
print('Intercept "b":', b)

#3
Y_pred = a*X+b
print('Predicted values "Y_pred":', Y_pred)

#4
error = np.linalg.norm(Y_pred - Y)
print('Error norm:', error)

Slope "a": 0.6
Intercept "b": 2.2
Predicted values "Y_pred": [2.8 3.4 4.  4.6 5.2]
Error norm: 1.5491933384829666


EXERCISE 5 — Random Numbers

1. Generate 100 random integers between 50 and 150.
2. Generate 50 random floats between 0 and 1.
3. Generate slopes using np.random.uniform(0.1, 1.0, size=30).
4. Compute the norm between Y and each new slope applied to X.

In [70]:
# 1
random_ints = np.random.randint(low=50,high=150,size=100,dtype='int')
print('Random integers generated:')
print(random_ints)

# 2
random_floats = np.random.uniform(low=0,high=1,size=50)
print('Random floats generated:')
print(random_floats)

# 3
slopes = np.random.uniform(0.1,1.0,30)
print('Slopes generated:')
print(slopes)

# 4
norms = np.array([]) # empty array to store results

for slope in slopes:
  error_norm = np.linalg.norm(Y-slope*X) # compute norm for this slope
  norms = np.append(norms,error_norm) # add to array

print('Norms computed:')
print(norms)

Random integers generated:
[113  82 147  99 129  79  79 107  74  94 101  65  68  84 113  63 133 134
  56 122  67 117  84  51 109  62 115 147 135 102 102 141  87 128 148  76
  94  72 111 123  90 148 117  88  61  55 117 112  79 142 124  97 141 137
  56  57  71  79  98 122  72  95 136  84  54  63  86 113  81 149 120 134
  89  81 148 121 102  53  75 141  94 106 145 125 113  85  54  58 143  50
 106 105 128 103  75 140 134  60  70 128]
Random floats generated:
[0.36722233 0.00713217 0.77248068 0.95449659 0.15007432 0.35247727
 0.92954743 0.6644293  0.99618147 0.90929297 0.75834807 0.17300006
 0.53137496 0.34872008 0.25767133 0.2337544  0.00994517 0.88901703
 0.44313642 0.88028956 0.17751243 0.24537299 0.60170167 0.17715807
 0.83263388 0.20999375 0.18824785 0.93167802 0.37450961 0.60347132
 0.08350044 0.88846401 0.91843179 0.87194646 0.49050153 0.82414658
 0.89628956 0.71306488 0.67167494 0.74964801 0.73975333 0.22705353
 0.12704242 0.63234176 0.16557206 0.67129211 0.2202466  0.55569974
 0.33

EXERCISE 6 — Challenge

Using everything above:
1. Create 200 random slopes between 0.1 and 2.0
2. Compute the norm for each slope
3. Stack results into a (200, 2) matrix: [error_norm, slope]
4. Save as a CSV

In [71]:
# 1
slopes_challenge = np.random.uniform(0.1,2.0,200)

# 2
norms_challenge = np.array([])

for slope in slopes_challenge:
    error_norm = np.linalg.norm(Y - slope * X)
    norms_challenge = np.append(norms_challenge, error_norm)

# 3
results = np.column_stack([norms_challenge, slopes_challenge])

# 4
np.savetxt('results.csv', results, delimiter=',',header='error_norm,slope')